# Generated by Django 2.0.2 on 2018-02-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0002_auto_20180216_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
