# Generated by Django 2.0.2 on 2018-02-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0004_bet_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='result',
            new_name='won',
        ),
    ]
