# Generated by Django 2.0.2 on 2018-02-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0006_bet_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
