# Generated by Django 2.0.2 on 2018-02-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0008_remove_bet_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Single'), (1, 'Accu'), (2, 'Combined'), (3, 'Live')], default=0),
            preserve_default=False,
        ),
    ]
