# Generated by Django 2.0.2 on 2018-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0009_bet_bet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Single'), (1, 'Accu'), (2, 'Combined'), (3, 'Live'), (4, 'Max')]),
        ),
    ]
