# Generated by Django 2.0.2 on 2018-02-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0012_bet_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
